### ISSUE TITLE
 implicit declaration of function ‘kill' 

### ISSUE THREAD

**Issue by LwsBtlr** [kevinboone/epub2txt2#13]
When trying to build under macOS I get:

```$ make
gcc -Wall -fPIC -fPIE -g -DVERSION=\"2.02\" -DAPPNAME=\"epub2txt\" -MD -MF build//epub2txt.deps -c -o build//epub2txt.o src//epub2txt.c
src//epub2txt.c:431:7: error: implicit declaration of function 'kill' is invalid in C99
      [-Werror,-Wimplicit-function-declaration]
      kill (getppid(), SIGTERM);
      ^
1 error generated.
make: *** [build//epub2txt.o] Error 1```

**Comment by teamcoltra** [comment]
Between line 10 and 11 on epub2text.c can you add 
#include <signal.h>
And tell me if that works for you?

**Comment by ismayilkarimli** [comment]
The solution submitted by @teamcoltra solved the issue with 'make' command in my case. However, later I experienced issues when trying to execute 'sudo make install'. To resolve, I deleted the preceding '/' from PREFIX, BINDIR, MANDIR variables in Makefile. Furthermore, for the latest versions (since El Capitan if I am not mistaken) of the MacOS Apple does not allow the modification of the /usr/bin even with sudo, however, there is no such restriction with /usr/local/. Therefore, I modified PREFIX to be usr/local. Final result looks like the following:

PREFIX  := usr/local
BINDIR  := bin
MANDIR  := share/man

**Comment by kevinboone** [comment]
Thanks for the suggestion. I've committed the change to add signal.h -- it should always have been there, but I guess by a fluke it doesn't seem to be needed on Linux. As for the problem with PREFIX, etc. -- I cross-compile this software for different platforms, and I use DESTDIR and PREFIX so that 'make install' populates a staging directory with the right structure. I haven't explained any of this, because I assumed (probably wrongly) that the defaults are OK. On Linux, it doesn't cause any problems when pathnames have a bunch of redundant / characters. So "///usr//local//bin" (or whatever) is perfectly OK. If that's _not_ true on Mac, I need to investigate. It's tricky, though, because I don't have a Mac to test on.

**Comment by paper42** [comment]
`/usr/local` prefix is standard even in the Linux world. Nothing should touch directories managed by the package manager like `/usr/bin`. Multiple / in a path shouldn't matter afaik.

**Comment by kevinboone** [comment]
Sure. I'm just unsure why ismayilkarimli had to remove some of the '/' characters from PREFIX, etc. As for /usr/local -- yes, it's commonplace on Linux as well. "make install PREFIX=/usr/local" should work (it did when I checked it on Linux, anyway)

**Comment by kevinboone** [comment]
I believe this issue is now fixed. Feel free to re-open it if not.
